"use client";

import { useEffect, useMemo, useState } from "react";
import Input from "@/components/form/input/InputField";
import Label from "@/components/form/Label";
import Select from "@/components/form/Select";
import Pagination from "@/components/tables/Pagination";
import { BellIcon, BoxCubeIcon, CalenderIcon, ChevronDownIcon, DollarLineIcon, GroupIcon, InfoIcon, PlugInIcon, UserCircleIcon } from "@/icons";
import { getActivityLogs, subscribeToActivityLogs } from "@/services/activity-log.service";
import { activityCategories, type ActivityCategory, type ActivityLog } from "@/types/activity-log";

const PAGE_SIZE = 10;

export default function ActivityLogPageClient({ initialLogs }: { initialLogs: ActivityLog[] }) {
  const [logs, setLogs] = useState(initialLogs); const [person, setPerson] = useState("all"); const [category, setCategory] = useState("all"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [page, setPage] = useState(1); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [error, setError] = useState("");
  const refresh = () => getActivityLogs().then(setLogs).catch(() => setError("Activity logs could not be loaded."));
  useEffect(() => { void refresh(); return subscribeToActivityLogs(refresh); }, []);
  const people = useMemo(() => Array.from(new Map(logs.map((log) => [log.actorId ?? `system:${log.actorName}`, { id: log.actorId ?? `system:${log.actorName}`, name: log.actorName }])).values()).sort((a, b) => a.name.localeCompare(b.name)), [logs]);
  const filtered = useMemo(() => logs.filter((log) => {
    const actorKey = log.actorId ?? `system:${log.actorName}`; const date = getBahrainDateKey(log.occurredAt);
    return (person === "all" || actorKey === person) && (category === "all" || log.category === category) && (!fromDate || date >= fromDate) && (!toDate || date <= toDate);
  }).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)), [logs, person, category, fromDate, toDate]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const visible = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  const groups = useMemo(() => visible.reduce<Record<string, ActivityLog[]>>((result, log) => { const key = getBahrainDateKey(log.occurredAt); (result[key] ??= []).push(log); return result; }, {}), [visible]);
  const resetPage = (setter: () => void) => { setter(); setPage(1); };
  const toggle = (id: string) => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90 sm:text-3xl">Activity Log</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">An append-only history of important activity across the business. Most recent first.</p></div><section aria-label="Activity filters" className="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.03] sm:p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Filter label="Person"><Select key={person} options={[{ value: "all", label: "Everyone" }, ...people.map((item) => ({ value: item.id, label: item.name }))]} defaultValue={person} onChange={(value) => resetPage(() => setPerson(value))} /></Filter><Filter label="Category"><Select key={category} options={[{ value: "all", label: "All categories" }, ...activityCategories.map((item) => ({ value: item, label: item }))]} defaultValue={category} onChange={(value) => resetPage(() => setCategory(value))} /></Filter><Filter label="From date"><Input type="date" value={fromDate} max={toDate || undefined} onChange={(event) => resetPage(() => setFromDate(event.target.value))} /></Filter><Filter label="To date"><Input type="date" value={toDate} min={fromDate || undefined} onChange={(event) => resetPage(() => setToDate(event.target.value))} /></Filter></div></section>{error ? <ErrorState message={error} onRetry={() => { setError(""); refresh(); }} /> : visible.length ? <div className="space-y-7">{Object.entries(groups).map(([date, entries]) => <section key={date} aria-labelledby={`date-${date}`}><div className="mb-3 flex items-center gap-3"><h2 id={`date-${date}`} className="shrink-0 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">{formatGroupDate(date)}</h2><span className="h-px w-full bg-gray-200 dark:bg-gray-800" /></div><div className="space-y-3">{entries.map((log) => <ActivityEntry key={log.id} log={log} expanded={expanded.has(log.id)} onToggle={() => toggle(log.id)} />)}</div></section>)}</div> : <EmptyState hasFilters={person !== "all" || category !== "all" || !!fromDate || !!toDate} />}{filtered.length > PAGE_SIZE && <div className="flex justify-center"><Pagination currentPage={safePage} totalPages={totalPages} onPageChange={setPage} /></div>}</div>;
}

function ActivityEntry({ log, expanded, onToggle }: { log: ActivityLog; expanded: boolean; onToggle: () => void }) {
  const detailRows = buildDetailRows(log);
  return <article className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><button type="button" aria-expanded={expanded} onClick={onToggle} className="flex w-full items-start gap-3 p-4 text-left transition hover:bg-gray-50 dark:hover:bg-white/[0.02]"><span className={`mt-0.5 inline-flex size-10 shrink-0 items-center justify-center rounded-lg ${categoryIconTone[log.category]}`}>{categoryIcon(log.category)}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="font-medium text-gray-800 dark:text-white/90">{log.action}</span><CategoryBadge category={log.category} /></span>{log.description && <span className="mt-1 block text-sm text-gray-500 dark:text-gray-400">{log.description}</span>}<span className="mt-1.5 block text-xs text-gray-400">{log.actorName} · {formatTime(log.occurredAt)}</span></span><ChevronDownIcon className={`mt-2 size-5 shrink-0 text-gray-400 transition-transform ${expanded ? "rotate-180" : ""}`} /></button>{expanded && <div className="border-t border-gray-100 bg-gray-50/70 px-4 py-4 dark:border-gray-800 dark:bg-gray-900/40"><dl className="grid gap-x-8 gap-y-3 text-sm md:grid-cols-2">{detailRows.map(([label, value]) => <div key={label} className="grid grid-cols-[110px_1fr] gap-3"><dt className="text-gray-400">{label}</dt><dd className="min-w-0 break-words text-gray-700 dark:text-gray-300">{value}</dd></div>)}</dl>{log.oldValues && <ValueBlock label="Old values" values={log.oldValues} />}{log.newValues && <ValueBlock label="New values" values={log.newValues} />}</div>}</article>;
}

function buildDetailRows(log: ActivityLog): [string, string][] {
  const rows: [string, string | undefined][] = [
    ["Email", log.actorEmail], ["Target", log.targetType], ["Record ID", log.targetId], ["IP address", log.ipAddress], ["Source", log.source],
    ...Object.entries(log.metadata).map(([key, value]) => [titleCase(key), formatValue(value)] as [string, string]),
  ];
  return rows.filter((row): row is [string, string] => row[1] !== undefined && row[1] !== "");
}

function ValueBlock({ label, values }: { label: string; values: Record<string, unknown> }) { return <div className="mt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">{label}</p><div className="grid gap-2 rounded-lg border border-gray-200 bg-white p-3 text-sm dark:border-gray-800 dark:bg-gray-900 sm:grid-cols-2">{Object.entries(values).map(([key, value]) => <div key={key} className="flex gap-2"><span className="text-gray-400">{titleCase(key)}:</span><span className="break-all text-gray-700 dark:text-gray-300">{formatValue(value)}</span></div>)}</div></div>; }
function Filter({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label>{children}</div>; }
function CategoryBadge({ category }: { category: ActivityCategory }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${categoryBadgeTone[category]}`}>{category}</span>; }
function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-400"><span>{message}</span><button type="button" className="font-medium underline" onClick={onRetry}>Try again</button></div>; }
function EmptyState({ hasFilters }: { hasFilters: boolean }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-gray-300 bg-gray-50 px-6 text-center dark:border-gray-700 dark:bg-white/[0.02]"><InfoIcon className="mb-3 size-8 text-gray-400" /><h2 className="font-medium text-gray-800 dark:text-white/90">{hasFilters ? "No matching activity" : "No activity recorded yet"}</h2><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{hasFilters ? "Adjust the filters or date range." : "Important completed actions will appear here."}</p></div>; }

const categoryBadgeTone: Record<ActivityCategory, string> = { Account: "bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-200", "Customers & Appointments": "bg-blue-light-50 text-blue-light-700 dark:bg-blue-light-500/15 dark:text-blue-light-400", "Catalog & Team": "bg-warning-50 text-warning-700 dark:bg-warning-500/15 dark:text-warning-400", Finance: "bg-success-50 text-success-700 dark:bg-success-500/15 dark:text-success-400", Expenses: "bg-orange-50 text-orange-700 dark:bg-orange-500/15 dark:text-orange-400", Settings: "bg-brand-50 text-brand-700 dark:bg-brand-500/15 dark:text-brand-400", Notifications: "bg-purple-50 text-purple-700 dark:bg-purple-500/15 dark:text-purple-400", Billing: "bg-success-50 text-success-700 dark:bg-success-500/15 dark:text-success-400", System: "bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-200" };
const categoryIconTone: Record<ActivityCategory, string> = { Account: "bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300", "Customers & Appointments": "bg-blue-light-50 text-blue-light-600 dark:bg-blue-light-500/15", "Catalog & Team": "bg-warning-50 text-warning-600 dark:bg-warning-500/15", Finance: "bg-success-50 text-success-600 dark:bg-success-500/15", Expenses: "bg-orange-50 text-orange-600 dark:bg-orange-500/15", Settings: "bg-brand-50 text-brand-600 dark:bg-brand-500/15", Notifications: "bg-purple-50 text-purple-600 dark:bg-purple-500/15", Billing: "bg-success-50 text-success-600 dark:bg-success-500/15", System: "bg-gray-100 text-gray-600 dark:bg-gray-700" };
function categoryIcon(category: ActivityCategory) { const className = "size-5"; switch (category) { case "Account": return <UserCircleIcon className={className} />; case "Customers & Appointments": return <CalenderIcon className={className} />; case "Catalog & Team": return <GroupIcon className={className} />; case "Finance": return <DollarLineIcon className={className} />; case "Expenses": return <BoxCubeIcon className={className} />; case "Settings": return <PlugInIcon className={className} />; case "Notifications": return <BellIcon className={className} />; case "Billing": return <DollarLineIcon className={className} />; default: return <InfoIcon className={className} />; } }
const titleCase = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/[_-]/g, " ").replace(/^./, (letter) => letter.toUpperCase()).trim();
const formatValue = (value: unknown): string => value === null ? "None" : typeof value === "object" ? JSON.stringify(value) : String(value);
const getBahrainDateKey = (iso: string) => { const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "Asia/Bahrain" }).formatToParts(new Date(iso)); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; };
const formatGroupDate = (date: string) => new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric", timeZone: "Asia/Bahrain" }).format(new Date(`${date}T12:00:00+03:00`));
const formatTime = (iso: string) => new Intl.DateTimeFormat("en-US", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit", timeZone: "Asia/Bahrain" }).format(new Date(iso));
