"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import Input from "@/components/form/input/InputField";
import Pagination from "@/components/tables/Pagination";
import Button from "@/components/ui/button/Button";
import { PlusIcon, SearchIcon } from "@/icons";
import { getTeamMembers, subscribeToTeamMembers } from "@/services/team-members.service";
import type { TeamMember } from "@/types/team-members";
import type { Branch } from "@/types/branches";
import type { Service } from "@/types/services";
import TeamMemberAvatar from "./TeamMemberAvatar";
import TeamMemberFormModal from "./TeamMemberFormModal";

const PAGE_SIZE = 8;
export default function TeamMembersPageClient({ initialMembers, branches, services }: { initialMembers: TeamMember[]; branches: Branch[]; services: Service[] }) {
  const [members, setMembers] = useState(initialMembers); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [modalOpen, setModalOpen] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => subscribeToTeamMembers(() => { getTeamMembers().then(setMembers).catch(() => setError("Team members could not be refreshed.")); }), []);
  const branchNames = useMemo(() => new Map(branches.map((branch) => [branch.id, branch.name])), [branches]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return !needle ? members : members.filter((member) => [member.fullName, member.email, member.phone, member.role].some((value) => value.toLowerCase().includes(needle))); }, [members, query]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((Math.min(page, totalPages) - 1) * PAGE_SIZE, Math.min(page, totalPages) * PAGE_SIZE);
  const changeQuery = (value: string) => { setQuery(value); setPage(1); };
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90 sm:text-3xl">Team Members</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{members.length} team member{members.length === 1 ? "" : "s"}</p></div><Button size="sm" startIcon={<PlusIcon />} onClick={() => setModalOpen(true)}>Add Team Member</Button></div>{notice && <div role="status" className="rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-700 dark:border-success-500/30 dark:bg-success-500/10 dark:text-success-400">{notice}</div>}{error && <ErrorState message={error} onRetry={() => { setError(""); getTeamMembers().then(setMembers).catch(() => setError("Team members could not be loaded.")); }} />}<div className="max-w-xl"><Input value={query} onChange={(event) => changeQuery(event.target.value)} placeholder="Search by name, email, phone or role..." ariaLabel="Search team members" startIcon={<SearchIcon />} /></div>{!error && (visible.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visible.map((member) => <Link key={member.id} href={`/settings/team-members/${member.id}`} className="group overflow-hidden rounded-2xl border border-gray-200 bg-white transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-theme-md dark:border-gray-800 dark:bg-white/[0.03] dark:hover:border-brand-500/50"><div className="flex h-36 items-center justify-center bg-gray-50 dark:bg-gray-800/60"><TeamMemberAvatar name={member.fullName} photoUrl={member.photoUrl} className="size-20 text-xl" /></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold text-gray-800 dark:text-white/90">{member.fullName}</h2><p className="mt-1 truncate text-sm text-gray-500 dark:text-gray-400">{member.email}</p></div><span className="text-xl text-gray-300 transition group-hover:translate-x-1 group-hover:text-brand-500">›</span></div><div className="mt-4 flex flex-wrap gap-2"><Badge tone="brand">{member.role}</Badge><Badge tone={member.status === "Active" ? "success" : member.status === "Inactive" ? "error" : "warning"}>{member.status}</Badge></div><p className="mt-4 text-xs text-gray-500 dark:text-gray-400">Branch: {branchNames.get(member.branchId) ?? "Unassigned"}</p></div></Link>)}</div> : <EmptyState searching={!!query} />)}{filtered.length > PAGE_SIZE && <div className="flex justify-center"><Pagination currentPage={Math.min(page, totalPages)} totalPages={totalPages} onPageChange={setPage} /></div>}<TeamMemberFormModal isOpen={modalOpen} onClose={() => setModalOpen(false)} branches={branches} services={services} onInvited={(message) => { setNotice(message); setError(""); }} /></div>;
}

function Badge({ tone, children }: { tone: "brand" | "success" | "warning" | "error"; children: React.ReactNode }) { const classes = { brand: "bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-400", success: "bg-success-50 text-success-700 dark:bg-success-500/15 dark:text-success-400", warning: "bg-warning-50 text-warning-700 dark:bg-warning-500/15 dark:text-warning-400", error: "bg-error-50 text-error-700 dark:bg-error-500/15 dark:text-error-400" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${classes[tone]}`}>{children}</span>; }
function EmptyState({ searching }: { searching: boolean }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-gray-300 bg-gray-50 px-6 text-center dark:border-gray-700 dark:bg-white/[0.02]"><h2 className="font-medium text-gray-800 dark:text-white/90">{searching ? "No matching team members" : "No team members yet"}</h2><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{searching ? "Try a different name, email, phone, or role." : "Invite your first team member to get started."}</p></div>; }
function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-400"><span>{message}</span><button type="button" className="font-medium underline" onClick={onRetry}>Try again</button></div>; }
