"use client";
import Image from "next/image";
import { BoxIcon, DownloadIcon } from "@/icons";
import { ServiceImageValidationError, uploadServiceImage } from "@/services/service-image-storage.service";

export default function ServiceImageField({ name, imageUrl, onChange, onError }: { name: string; imageUrl: string; onChange: (url: string) => void; onError: (message: string) => void }) {
  const upload = async (file?: File) => { if (!file) return; try { onChange(await uploadServiceImage(file)); } catch (reason) { onError(reason instanceof ServiceImageValidationError ? reason.message : "The image could not be uploaded."); } };
  return <div><p className="mb-2 text-sm font-medium text-gray-700 dark:text-gray-400">Service image <span className="font-normal text-gray-400">(optional)</span></p><div className="flex flex-wrap items-center gap-4"><div className="relative flex size-28 items-center justify-center overflow-hidden rounded-xl border border-dashed border-gray-300 bg-gray-50 dark:border-gray-700 dark:bg-gray-800">{imageUrl ? <Image src={imageUrl} alt={name || "Service preview"} fill unoptimized className="object-cover" /> : <BoxIcon className="size-7 text-gray-300" />}</div><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-medium text-gray-700 shadow-theme-xs transition hover:border-brand-300 hover:bg-brand-50 hover:text-brand-600 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300"><DownloadIcon className="size-5 rotate-180" />Upload image<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(event) => void upload(event.target.files?.[0])} /></label></div><p className="mt-2 text-xs text-gray-400">PNG, JPG or WebP · Maximum 3 MB</p></div>;
}
